### PR TITLE
Add JSONP Support

### PR DESCRIPTION
**Pull request by blowsie**
http://www.redmine.org/issues/13718#change-58154

### CODE REVIEW

**Comment by blowsie** [comment]
Just seen that you dont accept github requests, but perhaps someone your end could acknowledge this single character change that has been submitted to an issue that is over two years old.

Thanks!

**Comment by jbbarth** [comment]
You will have much higher chances to see your patch merged if you provide corresponding tests I guess. There are very few redmine maintainers (I'm not personally involved anymore) and they usually don't merge random changes without being 100% sure that it won't regress later. Good luck!

**Comment by jbbarth** [comment]
(btw I close the issue because we don't accept PRs here, this is just a mirror, the main source is on SVN at svn dot redmine dot org)

**Comment by blowsie** [comment]
I really don't see that tests are required for such a small regex change, it fairly obvious that the change moves redmine towards supporting the JSON specification.
I have used the change in production for over a year without any issues.

Sadly, working with SVN and Ruby is not my forte, therefore I wont be making and tests or additional commits.

It is sad that Redmine is not more open to input from their users, I guess that's why they have 4500 open tickets. Thanks for your time.

**Comment by marutosi** [comment]
> I really don't see that tests are required for such a small regex change

Almost all OpenSource projects require tests.
https://github.com/rails/rails/tree/v4.2.5#contributing
http://edgeguides.rubyonrails.org/contributing_to_ruby_on_rails.html#testing-patches

> It is sad that Redmine is not more open to input from their users, I guess that's why they have 4500 open tickets.

There are many open issues and PRs on Rails.
https://github.com/rails/rails/issues
https://github.com/rails/rails/pulls

**Comment by blowsie** [comment]
So where are the existing tests? The point i'm trying to make here is this is such a small change `.`, but for someone who does not use SVN or actively work on redmine, it seems rather difficult for me to help in any way at all. It would be great if someone could pick this just up and just implement it. Instead of being stale for 2 years.

**Comment by marutosi** [comment]
https://github.com/blowsie/redmine/blob/3c3bdb8bb07ef829c4c91de19545319b186a43fb/test/integration/api_test/jsonp_test.rb

**Comment by blowsie** [comment]
Well, one last try then.
https://bitbucket.org/redmine/redmine/pull-requests/3/improve-jsonp-support/diff

**Comment by marutosi** [comment]
http://www.redmine.org/projects/redmine/wiki/How_to_create_patch_series_on_Mercurial_and_Git

**Comment by blowsie** [comment]
Whats wrong with pull requests in bitbucket?

**Comment by marutosi** [comment]
http://www.redmine.org/projects/redmine/wiki/Contribute#Development

**Comment by marutosi** [comment]
I have updated wiki.
http://www.redmine.org/projects/redmine/wiki/Contribute/diff?utf8=%E2%9C%93&version=53&version_from=52&commit=View+differences

**Comment by marutosi** [comment]
> Whats wrong with pull requests in bitbucket?

http://www.redmine.org/issues/13718#note-10

Another reason is if GitHub and Bitbucket are closed, all records are lost.

**Pull request closed without merging**
