### PR TITLE
:x64_mingw -> Remove

### PR DESCRIPTION
**Pull request by salehi**
This is breakable in some systems.
Please remove it :)

### CODE REVIEW

**Comment by salehi** [comment]
`x64_mingw` is not a valid platform. The available options are: [:ruby, :ruby_18, :ruby_19, :mri, :mri_18, :mri_19, :rbx, :jruby, :mswin, :mingw, :mingw_18, :mingw_19]

**Comment by jbbarth** [comment]
Sorry but we don't accept pull requests on Github, I advise you submit your patch on https://redmine.org directly. I hope your contribution can be integrated soon. Thanks!

**Comment by salehi** [comment]
Can you explain a bit more please?
I want to contribute to redmine really.
Thanks.

**Comment by marutosi** [comment]
https://github.com/redmine/redmine/blob/3.0.0/CONTRIBUTING.md

**Comment by marutosi** [comment]
https://github.com/redmine/redmine/commit/f2d9af6dc32a67223e024c2acafce29355c9414c

**Pull request closed without merging**
