### PR TITLE
Update zh.yml to improve chinese user experience.

### PR DESCRIPTION
**Pull request by ky0nch3ng**
Update zh.yml to improve chinese user experience.

Old translation version have some issues for chinese users.

### CODE REVIEW

**Comment by vividtone** [comment]
I think that changing the translation for field_password  to "旧密码" (old password) will confuse Chinese users because field_password password is used in many pages and "old password" does not make sense in some pages. One example is app/views/account/login.html.erb.

**Comment by vividtone** [comment]
Please open a new issue on www.redmine.org when you suggest some changes. All issues are tracked on the site.

**Comment by ky0nch3ng** [comment]
Please review the zh-TW translastion.

https://github.com/redmine/redmine/blob/master/config/locales/zh-TW.yml

**Comment by vividtone** [comment]
Do you think the following login page (showing "旧密码" instead of "密码") is OK?

image

**Comment by ky0nch3ng** [comment]
/redmine/my/password

In this page.

**Pull request closed without merging**
