### PR TITLE
unnecessary translation of the macros {{toc}}

### PR DESCRIPTION
**Pull request by ozaryx**
____________________________________________________________________

Your contributions to Redmine are welcome!

Please **open an issue on the [official website]** instead of sending pull requests.

Since the development of Redmine is not conducted on GitHub but on the [official website] and core developers are not monitoring the GitHub repo, pull requests might not get reviewed.

For more detail about how to contribute, please see the wiki page [Contribute] on the [official website].

[official website]: https://www.redmine.org/
[Contribute]: https://www.redmine.org/projects/redmine/wiki/Contribute

### CODE REVIEW

**Comment by vividtone** [comment]
Could you post the patch on https://www.redmine.org/ ?

This is because the development of Redmine is not conducted on GitHub but on the official website. The repository on GitHub is a mirror of the official Subversion repository.

**Comment by ozaryx** [comment]
I'll try.

**Comment by ozaryx** [comment]
it seems to happened
https://www.redmine.org/issues/33939

Thank you for advice

**Comment by vividtone** [comment]
Thank you for your contribution. I am closing this issue.

**Pull request closed without merging**
